version: 2

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: restore
          command: dotnet restore

      - run:
          name: compile
          command: dotnet build

      - run:
          name: testing
          command: echo "dotnet test"

      - run:
          name: testing
          command: echo "dotnet publish"