version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: restore
          command: echo "dotnet restore"

      - run:
          name: compile
          command: echo "dotnet build"

      - run:
          name: testing
          command: echo "dotnet test"

      - run:
          name: testing
          command: echo "dotnet publish"