version: 2

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: restore
          command: dotnet restore ./source/cosmic.sln

      - run:
          name: compile
          command: dotnet build ./source/cosmic.sln --no-restore

      - run:
          name: testing
          command: dotnet test ./source/test/**/*.csproj --no-build --no-restore

      - run:
          name: publish
          command: dotnet publish ./source/cosmic.sln --no-build --no-restore -o ./pub
      
      - run:
          name: results
          command: ls -lR