# workflow name
name: build and deploy cosmic mobile app

# workflow events
on:
  push:
    paths:
    - "cosmic-mobile/**"
    - ".github/workflows/cosmic-mobile.yml"

# workflow env vars
env:
  DOCKER_URL: docker.pkg.github.com
  DOCKER_PATH: ${{ github.repository }}
  DOCKER_IMAGE: cosmic-mobile
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# workflow jobs
jobs:
  compile:
    name: build cosmic mobile app (android and ios)
    runs-on: ubuntu-latest
    env:
      COSMIC_MOBILE_TAG: ci
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: build dockerfile
        run: docker-compose build cosmic-mobile

  publish:
    name: deploy cosmic mobile app (github)
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: echo ${GITHUB_TOKEN} | docker login ${DOCKER_URL} -u ${GITHUB_ACTOR} --password-stdin

      - name: docker push to github packages
        run: docker push ${DOCKER_URL}/${DOCKER_PATH}/${DOCKER_IMAGE}:${COSMIC_MOBILE_TAG}