# workflow name
name: cosmic-mobile

# workflow events
on:
  push:
    paths:
    - "cosmic-mobile/**"
    - ".github/workflows/cosmic-mobile.yml"

# workflow env vars
env:
  DOCKER_URL: docker.pkg.github.com
  DOCKER_PATH: ${{ github.repository }}
  DOCKER_IMAGE: cosmic-mobile
  COSMIC_MOBILE_IMAGE: ${{ format('{0}/{1}/{2}', 'docker.pkg.github.com', github.repository, 'cosmic-mobile') }}
  COSMIC_MOBILE_VERSION: ci
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
# workflow jobs
jobs:
  compile:
    name: build cosmic mobile app (android and ios)
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: build dockerfile
        run: |
          docker build \
          -t ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION} \
          -t ${COSMIC_MOBILE_IMAGE}:latest \
          -f ./cosmic-mobile/Dockerfile ./cosmic-mobile
        
      - name: docker login
        run: echo ${GITHUB_TOKEN} | docker login ${DOCKER_URL} -u ${GITHUB_ACTOR} --password-stdin

      - name: docker push to github packages
        run: docker push ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION}