# workflow name
name: build and deploy cosmic mobile app

# workflow events
on:
  push:
    paths:
    - "cosmic-mobile/**"

# workflow jobs
jobs:
  compile:
    name: build cosmic mobile app (android and ios)
    runs-on: ubuntu-latest
    env:
      COSMIC_MOBILE_TAG: ci
    steps:
    - name: checkout source code
      uses: actions/checkout@v2

    - name: build dockerfile
      run: docker-compose build cosmic-mobile
      
  publish:
    name: deploy cosmic mobile app (github)
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - name: docker push to github packages
      run: echo "pushing to github"