# workflow name
name: cosmic-mobile

# workflow events
on:
  # another commit
  pull_request:
    branches:
      - master
    paths:
      - "cosmic-mobile/**"
      - ".github/workflows/cosmic-mobile.yml"
    types:
      - closed
      - edited
      - opened

# workflow env vars
env:
  DOCKER_URL: docker.pkg.github.com
  DOCKER_PATH: ${{ github.repository }}
  DOCKER_IMAGE: cosmic-mobile
  COSMIC_MOBILE_BUILD: ${{ github.run_id }}
  COSMIC_MOBILE_IMAGE: ${{ format('{0}/{1}/{2}', 'docker.pkg.github.com', github.repository, 'cosmic-mobile') }}
  COSMIC_MOBILE_VERSION: ${{ format('1.0.{0}', github.event.number) }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
# workflow jobs
jobs:
  compile:
    name: build cosmic mobile app
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build \
          -t ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION}-${COSMIC_MOBILE_BUILD} \
          -t ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION} \
          -t ${COSMIC_MOBILE_IMAGE}:latest \
          -f ./cosmic-mobile/Dockerfile ./cosmic-mobile
        
      - name: docker login
        run: echo ${GITHUB_TOKEN} | docker login ${DOCKER_URL} -u ${GITHUB_ACTOR} --password-stdin

      - name: docker push
        run: |
          docker push ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION}-${COSMIC_MOBILE_BUILD}
        if: github.event.action != 'closed'

      - name: docker push (production version)
        run: |
            docker push ${COSMIC_MOBILE_IMAGE}:${COSMIC_MOBILE_VERSION}
            docker push ${COSMIC_MOBILE_IMAGE}:latest
        if: github.event.action == 'closed' && github.event.pull_request.merged == true